import { technologyIcons } from "./technology-icons.constant";

export const technologyUrls: Record<keyof typeof technologyIcons, string> = {
  "google-cloud": "https://cloud.google.com/",
  apollo: "https://www.apollographql.com/",
  jest: "https://jestjs.io/",
  vscode: "https://code.visualstudio.com/",
  nvm: "https://github.com/nvm-sh/nvm",
  oracle: "https://www.oracle.com/database/",
  yarn: "https://yarnpkg.com/",
  pnpm: "https://pnpm.io/",
  storybook: "https://storybook.js.org/",
  "tanstack-query": "https://tanstack.com/query/latest",
  "react-router": "https://reactrouter.com/",
  graphql: "https://graphql.org/",
  bootstrap: "https://getbootstrap.com/",
  tailwind: "https://tailwindcss.com/",
  html: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  gitlab: "https://about.gitlab.com/",
  github: "https://github.com/",
  git: "https://git-scm.com/",
  threejs: "https://threejs.org/",
  javascript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  dbeaver: "https://dbeaver.io/",
  typescript: "https://www.typescriptlang.org/",
  express: "https://expressjs.com/",
  vite: "https://vitejs.dev/",
  postgresql: "https://www.postgresql.org/",
  docker: "https://www.docker.com/",
  nestjs: "https://nestjs.com/",
  react: "https://reactjs.org/",
  nextjs: "https://nextjs.org/",
  mongodb: "https://www.mongodb.com/",
  nodejs: "https://nodejs.org/",
  redis: "https://redis.io/",
};
