import { technologyIcons } from "./technology-icons.constant";

export const technologyNames: Record<keyof typeof technologyIcons, string> = {
  "google-cloud": "Google Cloud",
  apollo: "Apollo GraphQL",
  jest: "Jest",
  vscode: "VSCode",
  nvm: "NVM",
  oracle: "Oracle Database",
  yarn: "Yarn",
  pnpm: "PNPM",
  storybook: "Storybook",
  "tanstack-query": "TanStack Query",
  "react-router": "React Router",
  graphql: "GraphQL",
  bootstrap: "Bootstrap",
  tailwind: "Tailwind CSS",
  html: "HTML5",
  gitlab: "GitLab",
  github: "GitHub",
  git: "Git",
  threejs: "Three.js",
  javascript: "JavaScript",
  dbeaver: "DBeaver",
  typescript: "TypeScript",
  express: "Express.js",
  vite: "Vite",
  postgresql: "PostgreSQL",
  docker: "Docker",
  nestjs: "NestJS",
  react: "React",
  nextjs: "Next.js",
} as const;
