import { Sidebar } from "@/components/sidebar";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Icon } from "@/components/icon";
import { Footer } from "@/components/footer";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${robotoMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="h-screen flex flex-col">
        <ThemeProvider>
          <main className="h-full flex-1 flex">
            <Sidebar />
            <section className="flex-1 overflow-y-auto">
              {children}
              <Footer />
            </section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
